### ISSUE TITLE
Parse ModelicaStandardLibrary

### ISSUE THREAD

**Issue by beutlich** [lbl-srg/modelica-json#168]
Is it possible to parse the Modelica Standard Library? This is what I see:

```
Error: *** Error when parsing /mnt/c/Projekte/MSL/Modelica/package.mo: "java.lang.Exception: java.lang.StringIndexOutOfBoundsException: begin 15, end 0, length 14538
        at gov.lbl.parser.Main.moParser(Main.java:130)
        at gov.lbl.parser.Main.main(Main.java:53)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 15, end 0, length 14538
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at gov.lbl.parser.domain.Comment.findSubStr(Comment.java:595)
        at gov.lbl.parser.domain.Composition$AnnotationClass.annClass(Composition.java:65)
        at gov.lbl.parser.domain.Composition$AnnotationClass.access$100(Composition.java:54)
        at gov.lbl.parser.domain.Composition.<init>(Composition.java:49)
```

**Comment by mwetter** [comment]
@beutlich : The parser does not yet support the full Modelica syntax. Work is ongoing, in particular to better support replaceable and certain annotations.

**Comment by beutlich** [comment]
@mwetter Thanks for replying. My actual use case was to improve the MSL CI to see if there is a file comparisonSignals.txt provided for each example or test model. Thus, basically I would not require full Modelica language support, but just retrieving of model names having a StopTime annotation. Do you see any improvement in this direction? Thank you again?

**Comment by JayHuLBL** [comment]
@beutlich Improving the parsing of the annotation is one of the work we are doing now. Your user case will be covered after refactoring.
