### ISSUE TITLE
Tests fail on recent install

### ISSUE THREAD

**Issue by gtfierro** [lbl-srg/modelica-json#184]
Hi all! 

I followed the instructions [here](https://lbl-srg.github.io/modelica-json/) to install Modelica JSON locally, but when I run `npm test`, I get many errors of the following flavor:

```
error:   TypeError: Cannot read properties of undefined (reading 'split')
 JSON structure is
{
  "within": [
    "FromModelica"
  ],
  "class_definition": [
    {
      "class_prefixes": "block",
      "class_specifier": {
        "long_class_specifier": {
          "name": "Block1",
          "comment": "\"A block that instantiates nothing\"",
          "composition": {
            "element_list": {}
          }
        }
      }
    }
  ]
}
```

they all have a stack trace similar to

```
    at Object.toJSON (/home/gabe/src/NREL/modelica-json/lib/modelicaToJSON.js:53:13)
    at getJsons (/home/gabe/src/NREL/modelica-json/lib/parser.js:175:26)
    at Object.getJSON (/home/gabe/src/NREL/modelica-json/lib/parser.js:152:21)
    at Object.<anonymous> (/home/gabe/src/NREL/modelica-json/app.js:89:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```

I get the same errors when I try to convert any Modelica file I have access to. Can anyone else reproduce this error? Or is there an issue with my local installation?

**Comment by mwetter** [comment]
@anandkp92 @JayHuLBL : Does this still persist?
