### ISSUE TITLE
error while generating cxfCore

### ISSUE THREAD

**Issue by anandkp92** [lbl-srg/modelica-json#250]
```
node app.js -f ~/Programming/modelica/modelica-buildings/Buildings/Controls/OBC/CDL -o cxf --elementary --cxfCore 
/Users/akprakash/Programming/modelica/test/modelica-json/lib/objectExtractor.js:353
              if ('simple_expression' in subscript.expression) {
                                      ^

TypeError: Cannot use 'in' operator to search for 'simple_expression' in undefined
    at /Users/akprakash/Programming/modelica/test/modelica-json/lib/objectExtractor.js:353:39
    at Array.forEach (<anonymous>)
    at extractFromElementList (/Users/akprakash/Programming/modelica/test/modelica-json/lib/objectExtractor.js:351:60)
    at extractFromComposition (/Users/akprakash/Programming/modelica/test/modelica-json/lib/objectExtractor.js:228:21)
    at extractFromLongClassSpecifier (/Users/akprakash/Programming/modelica/test/modelica-json/lib/objectExtractor.js:194:27)
    at Object.extractAllObjects (/Users/akprakash/Programming/modelica/test/modelica-json/lib/objectExtractor.js:106:29)
    at generateAllObjectsJson (/Users/akprakash/Programming/modelica/test/modelica-json/lib/parser.js:156:29)
    at getSimpleJson (/Users/akprakash/Programming/modelica/test/modelica-json/lib/parser.js:144:28)
    at /Users/akprakash/Programming/modelica/test/modelica-json/lib/parser.js:55:14
    at Array.forEach (<anonymous>)
    at Object.getJsons (/Users/akprakash/Programming/modelica/test/modelica-json/lib/parser.js:49:13)
    at /Users/akprakash/Programming/modelica/test/modelica-json/app.js:126:10
    at new Promise (<anonymous>)
    at Object.<anonymous> (/Users/akprakash/Programming/modelica/test/modelica-json/app.js:122:35)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)

Node.js v20.9.0
```

**Comment by anandkp92** [comment]
Another issue: After generating CXFCore.jsonld, if its removed, but the CXF files still exist, CXFCore is not re-generated.

**Comment by anandkp92** [comment]
Tracking fixes in this [branch](https://github.com/lbl-srg/modelica-json/tree/issue250_errorCxfCore).
